name: acceptance-single-artifact

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions: {}
    runs-on: ubuntu-latest

    steps:
      - name: create test artifact
        run: |
          mkdir -p dist
          echo "test artifact" > dist/test-artifact.txt

      - name: upload artifact
        uses: actions/upload-artifact@4.6.2
        with:
          name: single-test-artifact
          path: dist/

  sign:
    needs: build
    permissions:
      id-token: write
      attestations: write
      contents: read
    uses: ./.github/workflows/sign-artifact.yml
    with:
      artifact-path: "."

  verify:
    needs: sign
    uses: ./.github/workflows/verify.yml
    with:
      artifact-path: "."
